INSERT IGNORE INTO  `s_ticket_support_mails` (`name`, `description`, `frommail`, `fromname`, `subject`, `content`, `contentHTML`, `ishtml`, `attachment`, `sys_dependent`, `isocode`,`shop_id`) VALUES
('sSTRAIGHTANSWER', 'Kundenbenachrichtigung - registriert', 'info@example.com', 'Shopware Demo Auto', 'Antwort zu Ihrem Ticket {sTicketID}', 'Hallo,\r\n  \r\nin Ihrem "Mein-Konto"-Bereich liegt eine Anwort auf Ihr Ticket {sTicketID} in der Supportverwaltung bereit. \r\n\r\nMit freundlichen Grüßen,\r\n \r\nIhr Team von Shopware.de', '', 0, '', 1, 'de', 1),
('sSTRAIGHTANSWER_UNREG', 'Kundenbenachrichtigung - unregistriert', 'info@example.com', 'Shopware Demo Auto', 'Antwort zu Ihrem Ticket {sTicketID}', '', 'Hallo,\r\n<br>  \r\nunter folgendem Link liegt eine Anwort auf Ihr Ticket {sTicketID} bereit. Hier haben Sie auch die Möglichkeit, auf diese zu reagieren.\r\n<br>\r\n<a href="{sTicketDirectUrl}">Ticketantwort einsehen</a>\r\n<br>\r\n<br>\r\nMit freundlichen Grüßen,<br>\r\n<br>\r\nIhr Team von Shopware.de', 1, '', 1, 'de', 1),
('sSTANDARD', 'Standardvorlage', 'info@example.com', 'Max Mustermann', 'Antwort zu Ihrem Ticket {sTicketID}', 'Standardvorlage \r\nAntwort auf das Ticket {sTicketID}', '\r\n', 0, '', 1, 'de', 1),
( '', 'RMA Defekt - abgelehnt', 'info@example.com', 'Shopware Demo', 'Ihre Rücksendung wegen Defekt wurde abgelehnt', ' Rücksendung wegen Defekt \r\n=========================\r\n\r\nHallo,\r\n\r\nleider müssen wir die Reklamation ablehnen, aus folgendem Grund: \r\n\r\n\r\n  \r\nViele Grüße\r\nShopware2.de', '', 0, '', 0, 'de', 1),
( '', 'RMA Rückgaberecht - akzeptiert', 'info@example.com', 'Shopware Demo', 'Ihre Rücksendung gemäß Rückgaberecht wurde akzeptiert', 'R Ü C K S E N D U N G   W E G E N  N I C H T G E F A L L E N S\r\n(gemäß 14 tägiges Widerrufsrecht nach Erhalt der Ware)\r\n==================================================\r\n\r\nHallo,\r\n\r\nbitte senden Sie den von Ihnen beschriebenen Artikel per Post, mit einer Rechnungskopie und unter Angabe des Grundes ausreichend frankiert zurück.\r\n\r\nBitte haben Sie Verständnis dafür das unfreie Sendungen nicht angenommen werden können.\r\n\r\nBitte senden Sie das Produkt innerhalb der nächsten 7 Tage originalverpackt inkl. allem Zubehör an uns zurück\r\nsowie ohne Gebrauchsspuren. Sollte sich die zurückgesendete Ware in einem Zustand befinden, in dem sie nicht\r\nals Neuware verkauft werden kann, müssen Sie mit einem Abzug für diese Wertminderung bei der Gutschrift rechnen.\r\n\r\n\r\nIhre Rücksendenummer lautet RMA{sTicketID} (Bitte deutlich auf das Paket schreiben)\r\n\r\nViele Grüße\r\nShopware2.de', '', 0, '', 0, 'de', 1),
( '', 'RMA Defekt - akzeptiert', 'info@example.com', 'Shopware Demo', 'Ihre Rücksendung wegen Defekt wurde akzeptiert', ' Rücksendung wegen Defekt \r\n=========================\r\n\r\nHallo,\r\nbitte senden Sie den von Ihnen beschriebenen Artikel \r\nper Post ausreichend frankiert zurück.\r\n\r\nUNFREIE SENDUNGEN KÖNNEN \r\nLEIDER NICHT ANGENOMMEN WERDEN.\r\n\r\nWir werden Ihnen bei berechtigter Reklamation die \r\nRücksendekosten gutschreiben.\r\n\r\nNach Überprüfung des Defektes durch \r\nunsere Techniker wird entschieden,  ob eine kurzfristige \r\nReparatur möglich ist, oder ob Sie einen Austausch\r\nfür den defekten Artikel erhalten. Danach wird der \r\nArtikel von uns zum Hersteller zur Reparatur bzw. zum \r\nAustausch geschickt. Im Anschluß an eine Reparatur \r\nwird der Artikel nochmals von uns getestet und Ihnen danach \r\nsofort zugestellt. Dauert eine Reparatur wider Erwarten zu lange, \r\nwird mit Ihnen abgestimmt, ob doch ein Austausch von \r\nuns vorgenommen wird.\r\n\r\nWir bitten Sie um Verständnis, dass wir nur bei tat-\r\nsächlich vorhandenen Mängeln einen Austausch \r\noder eine für Sie kostenlose Reparatur vornehmen können. \r\nSollte hingegen kein Mangel vorliegen, so behalten wir uns vor, \r\nunseren Überprüfungsaufwand und die Rück-\r\nsendekosten an Sie in Rechnung zu stellen.\r\n\r\nIhre Rücksendenummer lautet RMA{sTicketID} \r\n(Bitte deutlich auf das Paket schreiben) \r\n\r\nWenn Sie bereits eine ausführliche Fehlerbeschreibung in das\r\nOnline-Service-Formular geschrieben haben, müssen Sie der\r\nRücksendung keine Fehlerbeschreibung mehr beilegen.\r\n\r\nViele Grüße\r\nShopware2.de', '', 0, '', 0, 'de', 1),
( '', 'RMA Rückgaberecht - abgelehnt', 'info@example.com', 'Shopware Demo', 'Ihre Rücksendung gemäß Rückgaberecht wurde abgelehnt', 'Rücksendung wegen Widerrufsrecht\r\n======================================\r\n\r\nHallo,\r\n\r\nleider müssen wir Ihren Widerruf ablehnen, aus folgendem Grund: \r\n\r\n\r\n\r\nViele Grüße\r\nShopware2.de', '', 0, '', 0, 'de', 1),
( 'sTICKETNOTIFYMAILNEW', 'Benachrichtigung - Neues Ticket', 'info@example.com', 'Mein Absendername', 'Es liegt ein neues Ticket vor', 'Es liegt ein neues Ticket für Sie bereit. Die TicketID lautet: {sTicketID}', 'Es liegt ein neues Ticket für Sie bereit. Die TicketID lautet: {sTicketID}', 1, '', 1, 'de', 1),
( 'sTICKETNOTIFYMAILANS', 'Benachrichtigung - Beantwortetes Ticket', 'info@example.com', 'Mein Absendername', 'Es liegt eine Ticketantwort vor', 'Es liegt eine Antwort für das Ticket {sTicketID} für Sie bereit.', '', 0, '', 1, 'de', 1),
( 'sTICKETNOTIFYMAILCOSTUMER', 'Bestätigung - Kunde', 'info@example.com', 'Mein Absendername', 'Ihre Anfrage {sTicketID}', 'Vielen Dank für Ihre Anfrage mit der Nummer {sTicketID}. Wir werden uns in Kürze mit Ihnen in Verbindung setzen.', '', 0, '', 1, 'de', 1);
