name: Check JS code and run Jest tests

on:
    workflow_call:

permissions:
  contents: read

concurrency:
    group: js-lint-and-jest-${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
  js:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
          - uses: cachix/install-nix-action@v26
            with:
                github_access_token: ${{ secrets.GITHUB_TOKEN }}

          - uses: cachix/cachix-action@v12
            with:
                name: devenv

          - name: Install devenv.sh
            run: nix profile install github:cachix/devenv/v0.5
            shell: sh

          - run: devenv up &
          - run: devenv shell check-js-code
          - run: devenv shell test-jest
