name: Php Unit code coverage

on:
    workflow_call:

permissions:
    contents: read

concurrency:
    group: php-unit-code-coverage-${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    Code-Coverage:
        runs-on: ubuntu-latest
        env:
            TESTSUITE: 'all'

        steps:
            -   uses: actions/checkout@v2
            -   uses: cachix/install-nix-action@v20
                with:
                    github_access_token: ${{ secrets.GITHUB_TOKEN }}

            -   uses: cachix/cachix-action@v12
                with:
                    name: devenv

            -   name: Use Shopware Cache
                uses: cachix/cachix-action@v12
                with:
                    name: shopware
                    authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

            -   name: Install devenv.sh
                run: nix-env -if https://github.com/cachix/devenv/tarball/main

            -   name: Get Composer Cache Directory
                id: composer-cache
                run: |
                    echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            -   uses: actions/cache@v3
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-

            -   run: devenv shell info-setup
            -   run: sudo mount -t tmpfs tmpfs $(pwd)/.devenv/profile/lib/mysql -o size=4G
            -   run: devenv up &
            -   run: devenv shell ./.github/check-mysql.sh
            -   run: devenv shell test-phpunit-coverage-cobertura

            -   uses: codecov/codecov-action@v2
                with:
                    files: ./build/artifacts/phpunit-coverage-all.cobertura.xml
                    fail_ci_if_error: true
                    verbose: true
