name: End-to-End

on:
    workflow_call:

permissions:
  contents: read

concurrency:
    group: end-to-end-${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
  Mink:
    strategy:
      matrix:
          MINK_TAG: [
#              'account',
#              'checkout1',
#              'checkout2',
#              'detail',
#              'listing',
#              'note',
#              'sitemap',
#              'misc',
              'backend'
          ]
    runs-on: ubuntu-latest
    env:
        SW_HOST: localhost:8080
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: root
        DB_NAME: shopware
        MAILER_DSN: smtp://localhost:1025
        SW_BASE_PATH: ''
        SELENIUM_HOST: localhost
        SMTP_HOST: localhost
    services:
        database:
          image: mysql:8.0
          env:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: shopware
          options: '--mount="type=tmpfs,destination=/var/lib/mysql" --health-cmd="mysqladmin ping -h 127.0.0.1" --health-interval=5s --health-timeout=2s --health-retries=3'
          ports:
            - "3306:3306"
        mail:
          image: axllent/mailpit
          ports:
            - "1025:1025"
    steps:
        - uses: actions/checkout@v4
        - name: Start Selenium
          run: docker run -d --network host --shm-size 3g selenium/standalone-chrome:94.0
        - name: Get Composer Cache Directory
          id: composer-cache
          run: |
              echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

        - name: Cache Composer dependencies
          uses: actions/cache@v3
          with:
              path: ${{ steps.composer-cache.outputs.dir }}
              key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
              restore-keys: |
                  ${{ runner.os }}-composer-

        - name: Install Shopware
          run: make init

        - name: Prepare Mink tests
          run: make prepare-mink

        - name: Start Webserver
          run: ./build/server/start_server localhost

        - name: Run Mink tests
          run: vendor/bin/behat -vv --config=tests/Mink/behat.yml --format=pretty --out=std --tags ${{ matrix.MINK_TAG }}

        - name: Archive results
          if: always()
          uses: actions/upload-artifact@v3
          with:
              name: build data
              path: build/logs
