name: Run

on:
    workflow_dispatch:
    push:
    schedule:
        -   cron: '30 02 * * *'

concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    check-php-code:
        name: PHPStan and CSFixer
        uses: ./.github/workflows/check-php-code.yml
        secrets: inherit

    check-js-code:
        name: JsLinter and Jest tests
        uses: ./.github/workflows/check-js-code.yml
        secrets: inherit

    create-code-coverage:
        name: PhpUnit code coverage
        uses: ./.github/workflows/code-coverage.yml
        secrets: inherit
        needs: [ check-php-code, check-js-code ]

    php-unit:
        name: PHPUnit tests
        uses: ./.github/workflows/phpunit.yml
        secrets: inherit
        needs: [ create-code-coverage ]

    e2e-tests:
        name: E2E
        uses: ./.github/workflows/end-to-end.yml
        secrets: inherit
        needs: [ php-unit ]
